from rest_framework.authentication import BaseAuthentication
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework_simplejwt.exceptions import InvalidToken, AuthenticationFailed
from django.contrib.auth.models import AnonymousUser
from .models import GuestSession
import uuid

class LenientJWTAuthentication(JWTAuthentication):
    """
    Extends JWTAuthentication to allow fallback to GuestAuthentication
    if the JWT is invalid but a Guest ID is present.
    """
    def authenticate(self, request):
        try:
            return super().authenticate(request)
        except (InvalidToken, AuthenticationFailed) as e:
            # If X-Guest-Id is present, suppress the error so GuestAuthentication can run.
            if request.headers.get('X-Guest-Id'):
                return None
            # Otherwise, raise the error as usual (blocked).
            raise e

class GuestAuthentication(BaseAuthentication):
    """
    Custom authentication to handle Guest Mode via X-Guest-Id header.
    Does NOT return a User object, but attaches request.guest_session.
    """
    def authenticate(self, request):
        guest_id = request.headers.get('X-Guest-Id')
        device_label = request.headers.get('X-Guest-Device-Label')

        if not guest_id:
            return None

        try:
            uuid_obj = uuid.UUID(guest_id)
        except ValueError:
            return None

        # Create or retrieve the session based on the ID generated by the client
        session, created = GuestSession.objects.get_or_create(id=uuid_obj)

        if created and device_label:
            session.device_label = device_label
            session.save()
        else:
            # Touch the session to update last_seen_at
            session.save()

        # Attach the session to the request for permission checks
        request.guest_session = session

        # Return AnonymousUser so request.user is not None (DRF standard)
        return (AnonymousUser(), None)
