# Generated by Django 6.0.2 on 2026-02-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trialusagecounter",
            name="bot_tutor_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trialusagecounter",
            name="memory_run_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trialusagecounter",
            name="study_space_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trialusagecounter",
            name="tts_seconds_count",
            field=models.IntegerField(default=0),
        ),
    ]
