# Generated by Django 5.2.5 on 2025-10-04 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('avatar_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('voice', models.CharField(default='EnergeticYouth', max_length=50)),
                ('language', models.CharField(default='English', max_length=50)),
                ('publicity', models.CharField(choices=[('Private', 'Private'), ('Guests', 'Guests'), ('Public', 'Public')], default='Public', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
