# Generated by Django 5.2.5 on 2025-10-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='suggestion1',
            field=models.CharField(blank=True, help_text='First suggested prompt.', max_length=128),
        ),
        migrations.AddField(
            model_name='bot',
            name='suggestion2',
            field=models.CharField(blank=True, help_text='Second suggested prompt.', max_length=128),
        ),
        migrations.AddField(
            model_name='bot',
            name='suggestion3',
            field=models.CharField(blank=True, help_text='Third suggested prompt.', max_length=128),
        ),
    ]
