# Generated by Django 5.2.5 on 2025-12-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_bot_suggestion1_bot_suggestion2_bot_suggestion3'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='allow_web_search',
            field=models.BooleanField(default=False),
        ),
    ]
