# Generated by Django 5.2.5 on 2025-10-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_category_bot_is_official_bot_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='category',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='language',
        ),
        migrations.AddField(
            model_name='bot',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='bots', to='bots.category'),
        ),
    ]
