# Generated by Django 6.0.1 on 2026-01-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0003_bot_allow_web_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="bot_backgrounds/"
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="theme_color",
            field=models.CharField(default="#818cf8", max_length=20),
        ),
    ]
