# Generated by Django 5.2.5 on 2025-10-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_remove_bot_category_remove_bot_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='translation_key',
            field=models.SlugField(blank=True, help_text="A unique key for the frontend to use for translation, e.g., 'productivity'.", max_length=100, null=True, unique=True),
        ),
    ]
