# Generated by Django 5.2.5 on 2025-10-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_category_translation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='description',
            field=models.CharField(blank=True, help_text='A short description of what the bot does.', max_length=255),
        ),
    ]
