# Generated by Django 6.0.1 on 2026-01-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0004_bot_background_image_bot_theme_color"),
        ("studio", "0004_studyspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="study_spaces",
            field=models.ManyToManyField(
                blank=True, related_name="bots", to="studio.studyspace"
            ),
        ),
    ]
