# Generated by Django 6.0.1 on 2026-01-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0005_bot_study_spaces"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bot",
            name="background_image",
        ),
        migrations.RemoveField(
            model_name="bot",
            name="theme_color",
        ),
        migrations.AddField(
            model_name="bot",
            name="strict_context",
            field=models.BooleanField(default=False),
        ),
    ]
