# Generated by Django 5.2.5 on 2025-10-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_bot_subscribers_alter_bot_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='bot_avatars/'),
        ),
    ]
