# Generated by Django 5.1.5 on 2026-02-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0006_remove_bot_background_image_remove_bot_theme_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="voice",
            field=models.CharField(
                choices=[
                    ("energetic_youth", "Energetic Youth"),
                    ("calm_adult", "Calm Adult"),
                    ("professor", "Professor"),
                    ("storyteller", "Storyteller"),
                ],
                default="energetic_youth",
                max_length=50,
            ),
        ),
    ]
