# Generated by Django 5.1.5 on 2026-02-11 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_guestsession"),
        ("bots", "0007_alter_bot_voice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="guest_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_bots",
                to="accounts.guestsession",
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_bots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
