# Generated by Django 5.1.5 on 2026-02-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0008_bot_guest_session_alter_bot_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bot",
            name="publicity",
            field=models.CharField(
                choices=[
                    ("Private", "Private"),
                    ("Guests", "Guests"),
                    ("Public", "Public"),
                ],
                default="Private",
                max_length=10,
            ),
        ),
    ]
