# Generated by Django 5.1.5 on 2026-02-12 13:19

from django.db import migrations

def migrate_existing_bots_to_private(apps, schema_editor):
    Bot = apps.get_model('bots', 'Bot')
    # Update all non-official bots to be PRIVATE
    Bot.objects.filter(is_official=False).update(publicity='Private')

class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0009_alter_bot_publicity"),
    ]

    operations = [
        migrations.RunPython(migrate_existing_bots_to_private),
    ]
