# Generated by Django 5.2.5 on 2025-11-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='duration',
            field=models.IntegerField(default=0, help_text='Audio duration in milliseconds'),
        ),
    ]
