# Generated by Django 5.2.5 on 2025-10-07 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-last_message_at']},
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 7, 21, 12, 59, 640600, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10),
        ),
    ]
