# Generated by Django 5.2.5 on 2025-10-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='suggestion1',
            field=models.CharField(blank=True, help_text='First follow-up suggestion.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='suggestion2',
            field=models.CharField(blank=True, help_text='Second follow-up suggestion.', max_length=128, null=True),
        ),
    ]
