# Generated by Django 5.2.5 on 2025-10-27 13:14

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_suggestion1_chatmessage_suggestion2'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=chat.models.chat_attachment_path),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('file', 'File')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
