# Generated by Django 5.2.5 on 2026-01-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chatmessage_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="extracted_text",
            field=models.TextField(
                blank=True,
                help_text="Cached content extracted from the attachment",
                null=True,
            ),
        ),
    ]
