# Generated by Django 5.2.5 on 2025-11-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_attachment_chatmessage_attachment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
