# Generated by Django 6.0.1 on 2026-01-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chatmessage_extracted_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="liked",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="feedback",
            field=models.CharField(
                blank=True,
                choices=[("like", "Like"), ("dislike", "Dislike")],
                max_length=10,
                null=True,
            ),
        ),
    ]
