# Generated by Django 6.0.1 on 2026-01-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_remove_chatmessage_liked_chatmessage_feedback"),
        ("studio", "0004_studyspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="sources",
            field=models.ManyToManyField(
                blank=True, related_name="chats", to="studio.knowledgesource"
            ),
        ),
    ]
