# Generated by Django 5.1.5 on 2026-02-06 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_chat_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatResponseMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sources_count", models.IntegerField(default=0)),
                ("cited_count", models.IntegerField(default=0)),
                ("has_citation", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="chat.chatmessage",
                    ),
                ),
            ],
        ),
    ]
