# Generated by Django 5.1.5 on 2026-02-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_chatresponsemetric"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="sources",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
