# Generated by Django 5.1.5 on 2026-02-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_chatmessage_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="TTSCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("text", models.TextField()),
                ("voice", models.CharField(max_length=50)),
                ("audio_file", models.FileField(upload_to="tts_cache/")),
                ("duration_ms", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
