# Generated by Django 5.1.5 on 2026-02-16 02:01

from pgvector.django import VectorField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_chat_guest_session_alter_chat_user"),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS vector;", reverse_sql="DROP EXTENSION IF EXISTS vector;"),
        migrations.CreateModel(
            name="VectorChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("content", models.TextField()),
                ("embedding", VectorField(dimensions=3072)),
                ("metadata", models.JSONField(default=dict)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("bot_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("type", models.CharField(db_index=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
