# Generated by Django 5.1.5 on 2026-02-16 02:01

from pgvector.django import VectorField
from django.db import migrations, models
from django.db import connection

def create_extension(apps, schema_editor):
    if schema_editor.connection.vendor != 'sqlite':
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector;")

def drop_extension(apps, schema_editor):
    if schema_editor.connection.vendor != 'sqlite':
        schema_editor.execute("DROP EXTENSION IF EXISTS vector;")

class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_chat_guest_session_alter_chat_user"),
    ]

    operations = [
        migrations.RunPython(create_extension, reverse_code=drop_extension),
        migrations.CreateModel(
            name="VectorChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                # Use TextField for sqlite fallback during tests if needed, but VectorField is specific to PG
                # For testing with SQLite, we might need to mock this or skip it.
                # However, VectorField might fail on SQLite even if we don't use it.
                # Let's try to keep it as is, but suppress the SQL execution.
                ("content", models.TextField()),
                ("embedding", VectorField(dimensions=3072)),
                ("metadata", models.JSONField(default=dict)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("bot_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("type", models.CharField(db_index=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
