# Generated by Django 5.1.5 on 2026-02-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_vectorchunk"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="warning",
            field=models.TextField(
                blank=True,
                help_text="Optional disclaimer/warning shown under message content",
                null=True,
            ),
        ),
    ]
