# Generated by Django 5.1.5 on 2026-02-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_chatmessage_warning"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Compressed summary of earlier messages.",
                null=True,
            ),
        ),
    ]
