# Generated by Django 5.2.5 on 2026-01-12 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0002_chatmessage_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SLIDE", "Slide"),
                            ("QUIZ", "Quiz"),
                            ("FLASHCARD", "Flashcard"),
                            ("SPREADSHEET", "Spreadsheet"),
                            ("WORKBOOK", "Workbook"),
                            ("PODCAST", "Podcast"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("content", models.JSONField(blank=True, null=True)),
                ("media_url", models.URLField(blank=True, null=True)),
                ("duration", models.CharField(blank=True, max_length=20, null=True)),
                ("score", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="chat.chat",
                    ),
                ),
            ],
        ),
    ]
