# Generated by Django 5.2.5 on 2026-01-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgeartifact",
            name="type",
            field=models.CharField(
                choices=[
                    ("SLIDE", "Slide"),
                    ("QUIZ", "Quiz"),
                    ("FLASHCARD", "Flashcard"),
                    ("SPREADSHEET", "Spreadsheet"),
                    ("WORKBOOK", "Workbook"),
                    ("PODCAST", "Podcast"),
                    ("SUMMARY", "Summary"),
                ],
                max_length=20,
            ),
        ),
    ]
