# Generated by Django 5.1.5 on 2026-02-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0005_studyspace_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgesource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("FILE", "File"),
                    ("URL", "URL"),
                    ("YOUTUBE", "YouTube"),
                    ("IMAGE", "Image"),
                ],
                default="FILE",
                max_length=20,
            ),
        ),
    ]
