# Generated by Django 5.1.5 on 2026-02-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0006_alter_knowledgesource_source_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgeartifact",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="knowledgeartifact",
            name="correlation_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgeartifact",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgeartifact",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgeartifact",
            name="stage",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("ASSEMBLING_CONTEXT", "Assembling Context"),
                    ("GENERATING", "Generating Content"),
                    ("RENDERING_EXPORT", "Rendering Export"),
                    ("READY", "Ready"),
                    ("ERROR", "Error"),
                ],
                default="QUEUED",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="knowledgeartifact",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
