# Generated by Django 5.1.5 on 2026-02-11 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_guestsession"),
        ("studio", "0007_knowledgeartifact_attempts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgesource",
            name="guest_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="knowledge_sources",
                to="accounts.guestsession",
            ),
        ),
        migrations.AddField(
            model_name="studyspace",
            name="guest_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="study_spaces",
                to="accounts.guestsession",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgesource",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="knowledge_sources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studyspace",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_spaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
