# Generated by Django 5.1.5 on 2026-02-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0008_knowledgesource_guest_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgeartifact",
            name="enqueued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgeartifact",
            name="job_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
