# Generated by Django 5.1.5 on 2026-02-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0009_knowledgeartifact_enqueued_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgeartifact",
            name="options_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
