# Generated by Django 5.1.5 on 2026-02-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_guestsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="trial_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
