# Generated by Django 5.1.5 on 2026-02-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_trial_ends_at_user_trial_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestsession",
            name="installation_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
