# Generated by Django 5.1.5 on 2026-02-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_guestsession_installation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestsession',
            name='installation_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
