"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

# Load .env if exists
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, ".env"))

print("SENDGRID_SENDER =", os.getenv("SENDGRID_SENDER"))

SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
SENDGRID_SENDER = os.getenv("SENDGRID_SENDER")


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.sendgrid.net"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "apikey"  # SendGrid exige usar literal "apikey"
EMAIL_HOST_PASSWORD = os.getenv("SENDGRID_API_KEY")
DEFAULT_FROM_EMAIL = os.getenv("SENDGRID_SENDER")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")



# Build paths inside the project like this: BASE_DIR / 'subdir'.


# SECURITY
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-secret")
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"
ALLOWED_HOSTS = ["*"]  # Change in production

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "corsheaders",

    "accounts",  # Custom app
    "bots",  # Custom app
    "chat",  # Custom app
    "explore", # Add this line
    "studio", # Add this line
    "django_rq",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # CORS for mobile apps
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "static/"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = "accounts.User"

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
}

# Simple JWT settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# CORS settings for mobile / React Native apps
CORS_ALLOWED_ORIGINS = [
    "exp://127.0.0.1:19000",  # Expo local example
]
CORS_ALLOW_ALL_ORIGINS = True  # You can tighten this in production

# Email backend for development (console)

# Optional basic rate-limiting config (requires django-ratelimit if used)
RATELIMIT_ENABLE = True

# config/settings.py
# ... (rest of your settings)

# --- Media Files Configuration (User-Uploaded Files) ---
# The absolute path to the directory where user-uploaded files will be stored.
# We'll create a 'media' folder in the project's root directory.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# The URL that will serve the media files.
MEDIA_URL = '/media/'

# --- ChromaDB Configuration (Long Term Memory) ---
# Define onde o banco de dados vetorial será salvo localmente.
CHROMA_DB_PATH = BASE_DIR / 'chroma_db_data'

# --- RAG / Studio Configuration ---
# Limite de tokens para contexto de geração de artefatos (RAG)
# Ajustado para 50k para balancear custo e qualidade.
MAX_RAG_CONTEXT_TOKENS = 50000

# ===== CONFIGURAÇÃO DE IA =====

# False = Gemini API (gratuito com GEMINI_API_KEY)
# True = Vertex AI (Google Cloud, requer projeto e credenciais)
USE_VERTEX_AI = False

# Configurações Vertex AI (preencha quando for migrar)
VERTEX_PROJECT_ID = os.getenv('VERTEX_PROJECT_ID', '')
VERTEX_LOCATION = os.getenv('VERTEX_LOCATION', 'us-central1')

# RQ Configuration
RQ_QUEUES = {
    'default': {
        'HOST': os.getenv('REDIS_HOST', 'localhost'),
        'PORT': int(os.getenv('REDIS_PORT', 6379)),
        'DB': 0,
        'DEFAULT_TIMEOUT': 360,
    },
}
