# Generated by Django 5.1.5 on 2026-02-11 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_guestsession"),
        ("explore", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="searchhistory",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="searchhistory",
            name="guest_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="search_history",
                to="accounts.guestsession",
            ),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="searchhistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "term"),
                name="unique_user_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="searchhistory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("guest_session__isnull", False)),
                fields=("guest_session", "term"),
                name="unique_guest_term",
            ),
        ),
    ]
